import type { Metadata } from 'next';
import './globals.css';
import CursorFollower from './components/CursorFollower';

export const metadata: Metadata = {
  title: 'Thefullsnacksdevs',
  icons: {
    icon: '/favicon.ico',
    shortcut: '/favicon.ico',
    apple: '/favicon.ico'
  },
  manifest: '/manifest.json',
  keywords: 'Thefullsnacksdevs, fullsnacksdevs, fullsnacks, snacksdevs',
  authors: [{ name: 'Thefullsnacksdevs', url: 'https://thefullsnacksdevs.com' }],
  creator: 'Thefullsnacksdevs',
  publisher: 'Thefullsnacksdevs',
  openGraph: {
    title: 'Thefullsnacksdevs',
    description: 'Thefullsnacksdevs',
    url: 'https://thefullsnacksdevs.com',
    siteName: 'Thefullsnacksdevs',
    images: [
      {
        url: '/og-image.png',
        width: 1200,
        height: 630,
        alt: 'Thefullsnacksdevs'
      }
    ],
    locale: 'en-US',
    type: 'website'
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Thefullsnacksdevs',
    description: 'Thefullsnacksdevs',
    images: [
      {
        url: '/og-image.png',
        width: 1200,
        height: 630,
        alt: 'Thefullsnacksdevs'
      }
    ],
    site: '@thefullsnacksdevs',
    creator: '@thefullsnacksdevs'
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    noarchive: false,
    noimageindex: false,
    notranslate: false
  },
  themeColor: '#000000',
  appleWebApp: {
    capable: true,
    statusBarStyle: 'default',
    title: 'Thefullsnacksdevs',
    startupImage: [
      '/apple-touch-icon.png',
      '/apple-touch-icon-120x120.png',
      '/apple-touch-icon-152x152.png',
      '/apple-touch-icon-167x167.png',
      '/apple-touch-icon-180x180.png',
      '/apple-touch-icon-192x192.png',
      '/apple-touch-icon-384x384.png',
      '/apple-touch-icon-512x512.png'
    ]
  },
  viewport: {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1
  },
  formatDetection: {
    email: false,
    address: false,
    telephone: false
  },
  alternates: {
    canonical: 'https://thefullsnacksdevs.com',
    languages: {
      'en-US': 'https://thefullsnacksdevs.com',
      'es-ES': 'https://thefullsnacksdevs.com/es',
      'fr-FR': 'https://thefullsnacksdevs.com/fr',
      'de-DE': 'https://thefullsnacksdevs.com/de',
      'zh-CN': 'https://thefullsnacksdevs.com/zh'
    }
  },
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased relative">
        {children}
        <CursorFollower />
      </body>
    </html>
  );
}
